dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
  dns-hijack:
    - 'any:53'
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  fallback:
    - https://dns.google/dns-query
    - https://1.1.1.1/dns-query
    - tls://1.0.0.1:853
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4

tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
